sudo: required
services:
  - docker
before_install:
  - docker build -t mahshadul/docker-react-app -f Dockerfile.dev .
  
script:
  - docker run mahshadul/docker-react-app npm run test -- --coverage
  
